// Language translations data
const translations = {
  he: {
    appTitle: "תכנון מעגל חשמלי",
    rxFinderTitle: "מוצא התנגדות והיגב ליחידת אורך של כבלים",
    materialLabel: "חומר:",
    copper: "נחושת",
    aluminium: "אלומיניום",
    coreLabel: "סוג כבל:",
    single: "חד-גידי",
    multi: "רב-גידי",
    areaLabel: "שטח חתך (A) [mm²]:",
    areaPlaceholder: "הזן או בחר שטח חתך",
    findBtn: "קבל r ו-x",

    // Calculator buttons
    cableImpedanceBtn: "עכבת כבל",
    voltageDropBtn: "מפל מתח",
    shortCircuit1PhBtn: "קצר חד-פאזי",
    shortCircuit3PhBtn: "קצר תלת-פאזי",
    showHideAllBtn: "הצג/הסתר הכל",
    rxFinderBtn: "מוצא r ו-x",

    calcTitle: "חישוב עכבת כבל",
    impedanceLegend: "Z # עכבה [Ω]",
    lengthLegend: "L # אורך כבל [km]",
    resistanceLegend: "r # התנגדות [Ω/km]",
    reactanceLegend: "x # היגב [Ω/km]",
    cablesLegend: "n # מספר כבלים במקביל",
    rValueLabel: "התנגדות (r) [Ω/km]:",
    rValuePlaceholder: "הזן ערך r",
    xValueLabel: "היגב (x) [Ω/km]:",
    xValuePlaceholder: "הזן ערך x",
    cableLengthLabel: "אורך כבל (L) [km]:",
    cableLengthPlaceholder: "הזן אורך כבל",
    numCablesLabel: "מספר כבלים במקביל (n):",
    numCablesPlaceholder: "הזן מספר כבלים",
    copyBtn: "העתק מלמעלה",
    calcBtn: "חשב עכבה",
    noDataFound: "לא נמצאו נתונים עבור A = {0} mm²",
    resistance: "התנגדות (r):",
    reactance: "היגב (x):",
    format: "פורמט",
    ohms: "אוהם (Ω)",
    milliohms: "מיליאוהם (mΩ)",
    cartesian: "קרטזי",
    polar: "פולארי",
    findFirst: "אנא מצא ערכי r ו-x תחילה",
    enterValid: "אנא הזן מספרים תקינים עבור r, x, אורך כבל ומספר כבלים",

    // Voltage Drop Calculator
    voltageDropTitle: "חישוב מפל מתח",
    voltageDropLegend: "∆V # מפל מתח [V]",
    kFactorLegend: "k # מקדם (√3 תלת-פאזי, 2 חד-פאזי)",
    loadCurrentLegend: "Ib # זרם עומס [A]",
    distanceLegend: "L # מרחק (כיוון אחד) [km]",
    conductorsLegend: "n # מספר מוליכים",
    phaseAngleLegend: "α # זווית פאזה [°]",
    phaseTypeLabel: "סוג מערכת:",
    singlePhase: "חד-פאזי",
    threePhase: "תלת-פאזי",
    loadCurrentLabel: "זרם עומס (Ib) [A]:",
    loadCurrentPlaceholder: "הזן זרם עומס",
    distanceLabel: "מרחק (L) [km]:",
    distancePlaceholder: "הזן מרחק",
    numConductorsLabel: "מספר מוליכים (n):",
    numConductorsPlaceholder: "הזן מספר מוליכים",
    vdRValueLabel: "התנגדות (r) [Ω/km]:",
    vdXValueLabel: "היגב (x) [Ω/km]:",
    powerFactorLabel: "Power Factor (PF):",
    powerFactorPlaceholder: "הזן PF (-1 עד 1)",
    phaseAngleLabel: "זווית פאזה (α) [°]:",
    phaseAnglePlaceholder: "הזן זווית פאזה",
    calculateVDBtn: "חשב מפל מתח",
    voltageDropResults: "תוצאות מפל מתח",
    voltageDrop: "מפל מתח (∆V)",
    kFactor: "מקדם k",
    loadCurrent: "זרם עומס (Ib)",
    distance: "מרחק (L)",
    numConductors: "מספר מוליכים (n)",
    phaseAngle: "זווית פאזה (α)",
    impedanceComponent: "רכיב עכבה",
    invalidPowerFactor: "ערך Power Factor חייב להיות בין -1 ל-1",
    invalidPhaseAngle: "אנא הזן זווית פאזה תקינה",
    invalidPhaseAngleRange: "זווית פאזה חייבת להיות בין 0 ל-360 מעלות",
    enterValidVD: "אנא הזן מספרים תקינים עבור כל השדות",
    enterAngleValue: "אנא הזן ערך Power Factor או זווית פאזה",
    fromPF: "מ-PF",
    directInput: "הזנה ישירה",
    orText: "או",
  },
  en: {
    appTitle: "Electrical System Design",
    rxFinderTitle: "Cable Resistance & Reactance Per Unit of Length Finder",
    materialLabel: "Material:",
    copper: "Copper",
    aluminium: "Aluminium",
    coreLabel: "Core Type:",
    single: "Single-core",
    multi: "Multi-core",
    areaLabel: "Cross-sectional area (A) [mm²]:",
    areaPlaceholder: "Enter or select cross-sectional area",
    findBtn: "Get r and x",

    // Calculator buttons
    cableImpedanceBtn: "Cable Impedance",
    voltageDropBtn: "Voltage Drop",
    shortCircuit1PhBtn: "Short Circuit 1φ",
    shortCircuit3PhBtn: "Short Circuit 3φ",
    showHideAllBtn: "Show/Hide All",
    rxFinderBtn: "R & X Finder",

    calcTitle: "Calculate Cable Impedance",
    impedanceLegend: "Z # Impedance [Ω]",
    lengthLegend: "L # Cable length [km]",
    resistanceLegend: "r # Resistance [Ω/km]",
    reactanceLegend: "x # Reactance [Ω/km]",
    cablesLegend: "n # Number of parallel cables",
    rValueLabel: "Resistance (r) [Ω/km]:",
    rValuePlaceholder: "Enter r value",
    xValueLabel: "Reactance (x) [Ω/km]:",
    xValuePlaceholder: "Enter x value",
    cableLengthLabel: "Cable Length (L) [km]:",
    cableLengthPlaceholder: "Enter cable length",
    numCablesLabel: "Number of parallel cables (n):",
    numCablesPlaceholder: "Enter number of cables",
    copyBtn: "Copy from above",
    calcBtn: "Calculate Impedance",
    noDataFound: "No data found for A = {0} mm²",
    resistance: "Resistance (r):",
    reactance: "Reactance (x):",
    format: "Format",
    ohms: "Ohms (Ω)",
    milliohms: "Milliohms (mΩ)",
    cartesian: "Cartesian",
    polar: "Polar",
    findFirst: "Please find r and x values first",
    enterValid: "Please enter valid numbers for r, x, cable length, and number of cables",

    // Voltage Drop Calculator
    voltageDropTitle: "Calculate Voltage Drop",
    voltageDropLegend: "∆V # Voltage Drop [V]",
    kFactorLegend: "k # Factor (√3 three-phase, 2 single-phase)",
    loadCurrentLegend: "Ib # Load current [A]",
    distanceLegend: "L # Distance (one-way) [km]",
    conductorsLegend: "n # Number of conductors",
    phaseAngleLegend: "α # Phase angle [°]",
    phaseTypeLabel: "System Type:",
    singlePhase: "Single-phase",
    threePhase: "Three-phase",
    loadCurrentLabel: "Load Current (Ib) [A]:",
    loadCurrentPlaceholder: "Enter load current",
    distanceLabel: "Distance (L) [km]:",
    distancePlaceholder: "Enter distance",
    numConductorsLabel: "Number of Conductors (n):",
    numConductorsPlaceholder: "Enter number of conductors",
    vdRValueLabel: "Resistance (r) [Ω/km]:",
    vdXValueLabel: "Reactance (x) [Ω/km]:",
    powerFactorLabel: "Power Factor (PF):",
    powerFactorPlaceholder: "Enter PF (-1 to 1)",
    phaseAngleLabel: "Phase Angle (α) [°]:",
    phaseAnglePlaceholder: "Enter phase angle",
    calculateVDBtn: "Calculate Voltage Drop",
    voltageDropResults: "Voltage Drop Results",
    voltageDrop: "Voltage Drop (∆V)",
    kFactor: "k Factor",
    loadCurrent: "Load Current (Ib)",
    distance: "Distance (L)",
    numConductors: "Number of Conductors (n)",
    phaseAngle: "Phase Angle (α)",
    impedanceComponent: "Impedance Component",
    invalidPowerFactor: "Power Factor value must be between -1 and 1",
    invalidPhaseAngle: "Please enter a valid phase angle",
    invalidPhaseAngleRange: "Phase angle must be between 0 and 360 degrees",
    enterValidVD: "Please enter valid numbers for all fields",
    enterAngleValue: "Please enter either Power Factor or Phase Angle value",
    fromPF: "from PF",
    directInput: "direct input",
    orText: "or",
  },
}

// Initialize the global namespace and expose translations
window.CableApp = window.CableApp || {}
window.CableApp.translations = translations

console.log("Language data loaded successfully!")
