// Language translations data
const translations = {
  he: {
    appTitle: "תכנון מעגל חשמלי",
    rxFinderTitle: "מוצא התנגדות והיגב ליחידת אורך של כבלים",
    materialLabel: "חומר:",
    copper: "נחושת",
    aluminium: "אלומיניום",
    coreLabel: "סוג כבל:",
    single: "חד-גידי",
    multi: "רב-גידי",
    areaLabel: "שטח חתך (A) [mm²]:",
    areaPlaceholder: "הזן או בחר שטח חתך",
    findBtn: "קבל r ו-x",

    // Calculator buttons
    cableImpedanceBtn: "עכבת כבל",
    voltageDropBtn: "מפל מתח",
    shortCircuit1PhBtn: "קצר חד-פאזי",
    shortCircuit3PhBtn: "קצר תלת-פאזי",
    showHideAllBtn: "הצג/הסתר הכל",
    rxFinderBtn: "מוצא r ו-x",

    calcTitle: "חישוב עכבת כבל",
    impedanceLegend: "Z # עכבה [Ω]",
    lengthLegend: "L # אורך כבל [km]",
    resistanceLegend: "r # התנגדות [Ω/km]",
    reactanceLegend: "x # היגב [Ω/km]",
    cablesLegend: "n # מספר כבלים במקביל",
    rValueLabel: "התנגדות (r) [Ω/km]:",
    rValuePlaceholder: "הזן ערך r",
    xValueLabel: "היגב (x) [Ω/km]:",
    xValuePlaceholder: "הזן ערך x",
    cableLengthLabel: "אורך כבל (L) [km]:",
    cableLengthPlaceholder: "הזן אורך כבל",
    numCablesLabel: "מספר כבלים במקביל (n):",
    numCablesPlaceholder: "הזן מספר כבלים",
    copyBtn: "העתק מלמעלה",
    calcBtn: "חשב עכבה",
    noDataFound: "לא נמצאו נתונים עבור A = {0} mm²",
    resistance: "התנגדות (r):",
    reactance: "היגב (x):",
    format: "פורמט",
    ohms: "אוהם (Ω)",
    milliohms: "מיליאוהם (mΩ)",
    cartesian: "קרטזי",
    polar: "פולארי",
    findFirst: "אנא מצא ערכי r ו-x תחילה",
    enterValid: "אנא הזן מספרים תקינים עבור r, x, אורך כבל ומספר כבלים",

    // Voltage Drop Calculator
    voltageDropTitle: "חישוב מפל מתח",
    voltageDropLegend: "∆V # מפל מתח [V]",
    kFactorLegend: "k # מקדם (√3 תלת-פאזי, 2 חד-פאזי)",
    loadCurrentLegend: "Ib # זרם עומס [A]",
    distanceLegend: "L # אורך כבל [km]",
    conductorsLegend: "n # מספר כבלים לפאזה",
    phaseAngleLegend: "α # הפרש מופע [°]",

    // New voltage drop total equation
    totalVoltageLegend: "∆VT # מפל מתח כולל [V]",
    partialVoltageLegend: "∆Vi # חישוב מפל מתח חלקי",
    numCalculationsLabel: "מספר חישובים (i):",
    numCalculationsPlaceholder: "הזן מספר חישובים",

    phaseTypeLabel: "סוג מערכת:",
    singlePhase: "חד-פאזי",
    threePhase: "תלת-פאזי",
    loadCurrentLabel: "זרם עומס (Ib) [A]:",
    loadCurrentPlaceholder: "הזן זרם עומס",
    distanceLabel: "אורך כבל (L) [km]:",
    distancePlaceholder: "הזן אורך כבל",
    numConductorsLabel: "מספר כבלים לפאזה (n):",
    numConductorsPlaceholder: "הזן מספר כבלים לפאזה",
    vdRValueLabel: "התנגדות כבל (r) [Ω/km]:",
    vdXValueLabel: "היגב כבל (x) [Ω/km]:",
    powerFactorLabel: "מקדם הספק (PF):",
    powerFactorPlaceholder: "הזן PF (-1 עד 1)",
    phaseAngleLabel: "הפרש מופע (α) [°]:",
    phaseAnglePlaceholder: "הזן הפרש מופע",
    calculateVDBtn: "חשב מפל מתח",
    voltageDropResults: "תוצאות מפל מתח",
    multipleVoltageDropResults: "תוצאות מפל מתח מרובות",
    voltageDrop: "מפל מתח (∆V)",
    kFactor: "מקדם k",
    loadCurrent: "זרם עומס (Ib)",
    distance: "אורך כבל (L)",
    numConductors: "מספר כבלים לפאזה (n)",
    phaseAngle: "הפרש מופע (α)",
    impedanceComponent: "רכיב עכבה",
    invalidPowerFactor: "ערך מקדם הספק חייב להיות בין -1 ל-1",
    invalidPhaseAngle: "אנא הזן הפרש מופע תקין",
    invalidPhaseAngleRange: "הפרש מופע חייב להיות בין 0 ל-360 מעלות",
    enterValidVD: "אנא הזן מספרים תקינים עבור כל השדות",
    enterAngleValue: "אנא הזן ערך מקדם הספק או הפרש מופע",
    fromPF: "מ-PF",
    directInput: "הזנה ישירה",
    orText: "או",

    // Loop mode
    loopProgress: "מחשב ∆V{current} מתוך {total}",
    cancelLoop: "ביטול (ESC)",
    rxFinderAvailable: "מוצא r ו-x זמין לשימוש במהלך החישובים המרובים",

    // Three-phase short circuit calculator
    shortCircuit3PhTitle: "חישוב קצר תלת-פאזי",
    sc3phCurrentLegend: "I<sub>k3ph</sub> # זרם קצר תלת-פאזי [A]",
    sc3phVoltageLegend: "Un # מתח נומינלי של רמה ספציפית במערכת החשמלית [V]",
    sc3phImpedanceLegend: "Z<sub>k3ph</sub> # עכבת קצר תלת-פאזי [Ω]",
    nominalVoltageLabel: "מתח נומינלי (Un) [V]:",
    nominalVoltagePlaceholder: "הזן מתח נומינלי",
    zk3phValueLabel: "עכבת קצר (Zk3ph) [Ω]:",
    zk3phValuePlaceholder: "חשב Zk3ph",
    calculateZk3phBtn: "חשב Zk3ph",
    calculateSc3phBtn: "חשב זרם קצר",
    zk3phModalTitle: "חישוב עכבת קצר Zk3ph",
    zk3phInstructions: "בחר רכיבים לחישוב עכבת הקצר:",
    transformersTitle: "שנאים",
    cablesTitle: "כבלים",
    generatorsTitle: "גנרטורים",
    motorsTitle: "מנועים",
    transformerLabel: "שנאי",
    cableLabel: "כבל",
    generatorLabel: "גנרטור",
    motorLabel: "מנוע",
    calculateZk3phModalBtn: "חשב Zk3ph",
    cancelZk3phBtn: "ביטול",
    zk3phSelectionTitle: "בחירת רכיבי עכבה:",
    ztrLabel: "עכבת שנאי (ZTR)",
    zlLabel: "עכבת כבל (ZL)",
    zsystemLabel: "עכבת מערכת (ZSystem)",
    zgLabel: "עכבת גנרטור (ZG)",
    ztrTransformersLabel: "מספר שנאים במקביל:",
    zlCablesLabel: "מספר כבלים שונים:",
    confirmImpedanceBtn: "אשר בחירת עכבות",
    includeImpedance: "כלול עכבה זו",
    quantity: "כמות",
    numTransformers: "מספר שנאים במקביל:",
    enterNumTransformers: "הזן מספר שנאים",
    transformerImpedance: "עכבת שנאי",
    cableImpedance: "עכבת כבל",
    systemImpedance: "עכבת מערכת",
    generatorImpedance: "עכבת גנרטור",
    enterNominalVoltage: "אנא הזן מתח נומינלי תקין",
    selectImpedanceTypes: "אנא בחר לפחות סוג עכבה אחד",
    enterValidTransformerData: "אנא הזן נתוני שנאי תקינים",
    enterValidCableData: "אנא הזן נתוני כבל תקינים",
    enterValidSystemData: "אנא הזן נתוני מערכת תקינים",
    enterValidGeneratorData: "אנא הזן נתוני גנרטור תקינים",
    zk3phCalculationResults: "תוצאות חישוב Zk3ph",
    component: "רכיב",
    details: "פרטים",
    impedance: "עכבה",
    totalZk3ph: 'סה"כ Zk3ph',
    shortCircuitResults: "תוצאות קצר תלת-פאזי",
    nominalVoltage: "מתח נומינלי",
    shortCircuitImpedance: "עכבת קצר",
    shortCircuitCurrent: "זרם קצר תלת-פאזי",
    enterValidSC3ph: "אנא הזן מספרים תקינים עבור מתח נומינלי ועכבת קצר",
    calculateImpedance: "חשב עכבה",
    transformerPower: "הספק נומינלי (Sn) [kVA]:",
    shortCircuitVoltage: "מתח קצר (Uk) [%]:",
    enterPower: "הזן הספק",
    enterSCVoltage: "הזן מתח קצר",
    shortCircuitPower: "הספק קצר (Sk) [MVA]:",
    enterSk: "הזן הספק קצר",
    generatorPower: "הספק הגנרטור (Sg) [kVA]:",
    subtransientReactance: "היגב תת-מעברי (Xd'') [%]:",
    enterXd: "הזן Xd''",
    copyFromRX: "העתק מ-R&X Finder",
    copyFromImpedance: "העתק מעכבת כבל",
    cableLength: "אורך כבל (L) [km]:",
    enterLength: "הזן אורך",
    numCables: "מספר כבלים במקביל (n):",
    enterNumCables: "הזן מספר כבלים",
    resistance: "התנגדות (r) [Ω/km]:",
    reactance: "היגב (x) [Ω/km]:",
    enterR: "הזן r",
    enterX: "הזן x",
    findRXFirst: "אנא מצא ערכי r ו-x תחילה",
    calculateImpedanceFirst: "אנא חשב עכבת כבל תחילה",
    calculated: "חושב",
    impedanceSelectionTitle: "בחירת רכיבי עכבה:",
    impedanceCalculationTitle: "חישוב עכבת קצר Zk3ph",
    shortCircuitPowerSystem: "הספק הקצר של המערכת (Sk) [MVA]:",
    subtransientReactanceGenerator: "מפל מתח היגבי של הגנרטור (Ux%) [%]:",
    totalTransformerImpedance: "עכבת שנאי",

    // Updated cable impedance equation labels
    rxMethodName: "חישוב לפי היגב והתנגדות ליחידת אורך",
    resistivityMethodName: "חישוב לפי שטח חתך והתנגדות סגולית",
    resistivityLabel: "התנגדות סגולית (ρ) [Ω⋅mm²/m]:",
    resistivityPlaceholder: "הזן ρ (למשל: 0.0175 או 1/57)",
    lengthMetersLabel: "אורך כבל (L) [m]:",
    lengthMetersPlaceholder: "הזן אורך במטרים",
    crossSectionalAreaLabel: "שטח חתך (A) [mm²]:",
    crossSectionalAreaPlaceholder: "הזן שטח חתך",
    reactanceX0Label: "היגב (X₀) [Ω/km]:",
    reactanceX0Placeholder: "הזן X₀",
    selectEquationMessage: "אנא בחר משוואה לחישוב",
    selectCableEquationInstruction: "בחר משוואה אחת לחישוב עכבת הכבל:",
    ztrTransformersLabel: "מספר שנאים כולל:",
    zgGeneratorsLabel: "מספר גנרטורים כולל:",

    // Calculation method modal
    calculationMethodTitle: "בחר שיטת חישוב",
    calculationMethodInstructions: "בחר את שיטת החישוב המתאימה:",
    standardCalculation: "חישוב סטנדרטי",
    standardCalculationDesc: "חישוב זרם קצר בסיסי ללא מקדמי בטיחות",
    safetyCalculation: "חישוב עם מקדם בטיחות",
    safetyCalculationDesc: "חישוב זרם קצר עם מקדם בטיחות 1.1 (מומלץ לתכנון)",
    calculateBtn: "חשב",
    cancelBtn: "ביטול",
    calculationMethod: "שיטת חישוב",
    calculationFormula: "נוסחת חישוב",
    safetyFactor: "מקדם בטיחות",
  },
  en: {
    appTitle: "Electrical System Design",
    rxFinderTitle: "Cable Resistance & Reactance Per Unit of Length Finder",
    materialLabel: "Material:",
    copper: "Copper",
    aluminium: "Aluminium",
    coreLabel: "Core Type:",
    single: "Single-core",
    multi: "Multi-core",
    areaLabel: "Cross-sectional area (A) [mm²]:",
    areaPlaceholder: "Enter or select cross-sectional area",
    findBtn: "Get r and x",

    // Calculator buttons
    cableImpedanceBtn: "Cable Impedance",
    voltageDropBtn: "Voltage Drop",
    shortCircuit1PhBtn: "Short Circuit 1φ",
    shortCircuit3PhBtn: "Short Circuit 3φ",
    showHideAllBtn: "Show/Hide All",
    rxFinderBtn: "R & X Finder",

    calcTitle: "Calculate Cable Impedance",
    impedanceLegend: "Z # Impedance [Ω]",
    lengthLegend: "L # Cable length [km]",
    resistanceLegend: "r # Resistance [Ω/km]",
    reactanceLegend: "x # Reactance [Ω/km]",
    cablesLegend: "n # Number of parallel cables",
    rValueLabel: "Resistance (r) [Ω/km]:",
    rValuePlaceholder: "Enter r value",
    xValueLabel: "Reactance (x) [Ω/km]:",
    xValuePlaceholder: "Enter x value",
    cableLengthLabel: "Cable Length (L) [km]:",
    cableLengthPlaceholder: "Enter cable length",
    numCablesLabel: "Number of parallel cables (n):",
    numCablesPlaceholder: "Enter number of cables",
    copyBtn: "Copy from above",
    calcBtn: "Calculate Impedance",
    noDataFound: "No data found for A = {0} mm²",
    resistance: "Resistance (r):",
    reactance: "Reactance (x):",
    format: "Format",
    ohms: "Ohms (Ω)",
    milliohms: "Milliohms (mΩ)",
    cartesian: "Cartesian",
    polar: "Polar",
    findFirst: "Please find r and x values first",
    enterValid: "Please enter valid numbers for r, x, cable length, and number of cables",

    // Voltage Drop Calculator
    voltageDropTitle: "Calculate Voltage Drop",
    voltageDropLegend: "∆V # Voltage Drop [V]",
    kFactorLegend: "k # Factor (√3 three-phase, 2 single-phase)",
    loadCurrentLegend: "Ib # Load current [A]",
    distanceLegend: "L # Cable length [km]",
    conductorsLegend: "n # Number of conductors per phase",
    phaseAngleLegend: "α # Phase angle [°]",

    // New voltage drop total equation
    totalVoltageLegend: "∆VT # Total voltage drop [V]",
    partialVoltageLegend: "∆Vi # Partial voltage drop calculation",
    numCalculationsLabel: "Number of calculations (i):",
    numCalculationsPlaceholder: "Enter number of calculations",

    phaseTypeLabel: "System Type:",
    singlePhase: "Single-phase",
    threePhase: "Three-phase",
    loadCurrentLabel: "Load Current (Ib) [A]:",
    loadCurrentPlaceholder: "Enter load current",
    distanceLabel: "Cable Length (L) [km]:",
    distancePlaceholder: "Enter cable length",
    numConductorsLabel: "Number of Conductors per Phase (n):",
    numConductorsPlaceholder: "Enter number of conductors per phase",
    vdRValueLabel: "Cable Resistance (r) [Ω/km]:",
    vdXValueLabel: "Cable Reactance (x) [Ω/km]:",
    powerFactorLabel: "Power Factor (PF):",
    powerFactorPlaceholder: "Enter PF (-1 to 1)",
    phaseAngleLabel: "Phase Angle (α) [°]:",
    phaseAnglePlaceholder: "Enter phase angle",
    calculateVDBtn: "Calculate Voltage Drop",
    voltageDropResults: "Voltage Drop Results",
    multipleVoltageDropResults: "Multiple Voltage Drop Results",
    voltageDrop: "Voltage Drop (∆V)",
    kFactor: "k Factor",
    loadCurrent: "Load Current (Ib)",
    distance: "Cable Length (L)",
    numConductors: "Number of Conductors per Phase (n)",
    phaseAngle: "Phase Angle (α)",
    impedanceComponent: "Impedance Component",
    invalidPowerFactor: "Power Factor value must be between -1 and 1",
    invalidPhaseAngle: "Please enter a valid phase angle",
    invalidPhaseAngleRange: "Phase angle must be between 0 and 360 degrees",
    enterValidVD: "Please enter valid numbers for all fields",
    enterAngleValue: "Please enter either Power Factor or Phase Angle value",
    fromPF: "from PF",
    directInput: "direct input",
    orText: "or",

    // Loop mode
    loopProgress: "Calculating ∆V{current} of {total}",
    cancelLoop: "Cancel (ESC)",
    rxFinderAvailable: "R&X Finder available for use during multiple calculations",

    // Three-phase short circuit calculator
    shortCircuit3PhTitle: "Three-Phase Short Circuit Calculation",
    sc3phCurrentLegend: "I<sub>k3ph</sub> # Three-phase short circuit current [A]",
    sc3phVoltageLegend: "Un # Nominal voltage of specific level in the electrical system [V]",
    sc3phImpedanceLegend: "Z<sub>k3ph</sub> # Three-phase short circuit impedance [Ω]",
    nominalVoltageLabel: "Nominal Voltage (Un) [V]:",
    nominalVoltagePlaceholder: "Enter nominal voltage",
    zk3phValueLabel: "Short Circuit Impedance (Zk3ph) [Ω]:",
    zk3phValuePlaceholder: "Calculate Zk3ph",
    calculateZk3phBtn: "Calculate Zk3ph",
    calculateSc3phBtn: "Calculate Short Circuit Current",
    zk3phModalTitle: "Calculate Short Circuit Impedance Zk3ph",
    zk3phInstructions: "Select components for short circuit impedance calculation:",
    transformersTitle: "Transformers",
    cablesTitle: "Cables",
    generatorsTitle: "Generators",
    motorsTitle: "Motors",
    transformerLabel: "Transformer",
    cableLabel: "Cable",
    generatorLabel: "Generator",
    motorLabel: "Motor",
    calculateZk3phModalBtn: "Calculate Zk3ph",
    cancelZk3phBtn: "Cancel",
    zk3phSelectionTitle: "Select Impedance Components:",
    ztrLabel: "Transformer Impedance (ZTR)",
    zlLabel: "Cable Impedance (ZL)",
    zsystemLabel: "System Impedance (ZSystem)",
    zgLabel: "Generator Impedance (ZG)",
    ztrTransformersLabel: "Number of transformers in series:",
    zlCablesLabel: "Number of different cables:",
    confirmImpedanceBtn: "Confirm Impedance Selection",
    includeImpedance: "Include this impedance",
    quantity: "Quantity",
    numTransformers: "Number of parallel transformers:",
    enterNumTransformers: "Enter number of transformers",
    transformerImpedance: "Transformer Impedance",
    cableImpedance: "Cable Impedance",
    systemImpedance: "System Impedance",
    generatorImpedance: "Generator Impedance",
    enterNominalVoltage: "Please enter a valid nominal voltage",
    selectImpedanceTypes: "Please select at least one impedance type",
    enterValidTransformerData: "Please enter valid transformer data",
    enterValidCableData: "Please enter valid cable data",
    enterValidSystemData: "Please enter valid system data",
    enterValidGeneratorData: "Please enter valid generator data",
    zk3phCalculationResults: "Zk3ph Calculation Results",
    component: "Component",
    details: "Details",
    impedance: "Impedance",
    totalZk3ph: "Total Zk3ph",
    shortCircuitResults: "Three-Phase Short Circuit Results",
    nominalVoltage: "Nominal Voltage",
    shortCircuitImpedance: "Short Circuit Impedance",
    shortCircuitCurrent: "Three-Phase Short Circuit Current",
    enterValidSC3ph: "Please enter valid numbers for nominal voltage and short circuit impedance",
    calculateImpedance: "Calculate Impedance",
    transformerPower: "Nominal Power (Sn) [kVA]:",
    shortCircuitVoltage: "Short Circuit Voltage (Uk) [%]:",
    enterPower: "Enter power",
    enterSCVoltage: "Enter short circuit voltage",
    shortCircuitPower: "Short Circuit Power (Sk) [MVA]:",
    enterSk: "Enter short circuit power",
    generatorPower: "Generator Power (Sg) [kVA]:",
    subtransientReactance: "Subtransient Reactance (Xd'') [%]:",
    enterXd: "Enter Xd''",
    copyFromRX: "Copy from R&X Finder",
    copyFromImpedance: "Copy from Cable Impedance",
    cableLength: "Cable Length (L) [km]:",
    enterLength: "Enter length",
    numCables: "Number of parallel cables (n):",
    enterNumCables: "Enter number of cables",
    resistance: "Resistance (r) [Ω/km]:",
    reactance: "Reactance (x) [Ω/km]:",
    enterR: "Enter r",
    enterX: "Enter x",
    findRXFirst: "Please find r and x values first",
    calculateImpedanceFirst: "Please calculate cable impedance first",
    calculated: "calculated",
    impedanceSelectionTitle: "Select Impedance Components:",
    impedanceCalculationTitle: "Calculating Short Circuit Impedance Zk3ph",
    shortCircuitPowerSystem: "Short Circuit Power (Sk) [MVA]:",
    subtransientReactanceGenerator: "Subtransient reactance of the generator (Ux%) [%]:",
    totalTransformerImpedance: "Total Transformer Impedance",

    // Updated cable impedance equation labels
    rxMethodName: "r and x per unit length method",
    resistivityMethodName: "Resistivity and cross-sectional area method",
    resistivityLabel: "Resistivity (ρ) [Ω⋅mm²/m]:",
    resistivityPlaceholder: "Enter ρ (e.g.: 0.0175 or 1/57)",
    lengthMetersLabel: "Cable Length (L) [m]:",
    lengthMetersPlaceholder: "Enter length in meters",
    crossSectionalAreaLabel: "Cross-sectional area (A) [mm²]:",
    crossSectionalAreaPlaceholder: "Enter cross-sectional area",
    reactanceX0Label: "Reactance (X₀) [Ω/km]:",
    reactanceX0Placeholder: "Enter X₀",
    selectEquationMessage: "Please select an equation for calculation",
    selectCableEquationInstruction: "Select one equation to calculate cable impedance:",
    ztrTransformersLabel: "Total number of transformers:",
    zgGeneratorsLabel: "Total number of generators:",

    // Calculation method modal
    calculationMethodTitle: "Select Calculation Method",
    calculationMethodInstructions: "Choose the appropriate calculation method:",
    standardCalculation: "Standard Calculation",
    standardCalculationDesc: "Basic short circuit current calculation without safety factors",
    safetyCalculation: "Safety Factor Calculation",
    safetyCalculationDesc: "Short circuit current calculation with 1.1 safety factor (recommended for design)",
    calculateBtn: "Calculate",
    cancelBtn: "Cancel",
    calculationMethod: "Calculation Method",
    calculationFormula: "Calculation Formula",
    safetyFactor: "Safety Factor",
  },
}

// Initialize the global namespace and expose translations
window.CableApp = window.CableApp || {}
window.CableApp.translations = translations

console.log("Enhanced language data loaded successfully!")
