// Language translations data
const translations = {
  he: {
    appTitle: "חישוב התנגדות והיגב כבלים",
    materialLabel: "חומר:",
    copper: "נחושת",
    aluminium: "אלומיניום",
    coreLabel: "סוג כבל:",
    single: "חד-גידי",
    multi: "רב-גידי",
    areaLabel: "שטח חתך (A) [mm²]:",
    areaPlaceholder: "הזן או בחר שטח חתך",
    findBtn: "קבל r ו-x",
    calcTitle: "חישוב עכבת כבל",
    impedanceLegend: "Z # עכבה [Ω]",
    lengthLegend: "L # אורך כבל [km]",
    resistanceLegend: "r # התנגדות [Ω/km]",
    reactanceLegend: "x # היגב [Ω/km]",
    cablesLegend: "n # מספר כבלים במקביל",
    rValueLabel: "התנגדות (r) [Ω/km]:",
    rValuePlaceholder: "הזן ערך r",
    xValueLabel: "היגב (x) [Ω/km]:",
    xValuePlaceholder: "הזן ערך x",
    cableLengthLabel: "אורך כבל (L) [km]:",
    cableLengthPlaceholder: "הזן אורך כבל",
    numCablesLabel: "מספר כבלים במקביל (n):",
    numCablesPlaceholder: "הזן מספר כבלים",
    copyBtn: "העתק מלמעלה",
    calcBtn: "חשב עכבה",
    noDataFound: "לא נמצאו נתונים עבור A = {0} mm²",
    resistance: "התנגדות (r):",
    reactance: "היגב (x):",
    format: "פורמט",
    ohms: "אוהם (Ω)",
    milliohms: "מיליאוהם (mΩ)",
    cartesian: "קרטזי",
    polar: "פולארי",
    findFirst: "אנא מצא ערכי r ו-x תחילה",
    enterValid: "אנא הזן מספרים תקינים עבור r, x, אורך כבל ומספר כבלים",
  },
  en: {
    appTitle: "Cable Resistance & Reactance Finder",
    materialLabel: "Material:",
    copper: "Copper",
    aluminium: "Aluminium",
    coreLabel: "Core Type:",
    single: "Single-core",
    multi: "Multi-core",
    areaLabel: "Cross-sectional area (A) [mm²]:",
    areaPlaceholder: "Enter or select cross-sectional area",
    findBtn: "Get r and x",
    calcTitle: "Calculate Cable Impedance",
    impedanceLegend: "Z # Impedance [Ω]",
    lengthLegend: "L # Cable length [km]",
    resistanceLegend: "r # Resistance [Ω/km]",
    reactanceLegend: "x # Reactance [Ω/km]",
    cablesLegend: "n # Number of parallel cables",
    rValueLabel: "Resistance (r) [Ω/km]:",
    rValuePlaceholder: "Enter r value",
    xValueLabel: "Reactance (x) [Ω/km]:",
    xValuePlaceholder: "Enter x value",
    cableLengthLabel: "Cable Length (L) [km]:",
    cableLengthPlaceholder: "Enter cable length",
    numCablesLabel: "Number of parallel cables (n):",
    numCablesPlaceholder: "Enter number of cables",
    copyBtn: "Copy from above",
    calcBtn: "Calculate Impedance",
    noDataFound: "No data found for A = {0} mm²",
    resistance: "Resistance (r):",
    reactance: "Reactance (x):",
    format: "Format",
    ohms: "Ohms (Ω)",
    milliohms: "Milliohms (mΩ)",
    cartesian: "Cartesian",
    polar: "Polar",
    findFirst: "Please find r and x values first",
    enterValid: "Please enter valid numbers for r, x, cable length, and number of cables",
  },
}

// Initialize the global namespace and expose translations
window.CableApp = window.CableApp || {}
window.CableApp.translations = translations